### ISSUE TITLE
Cache storage options (SQL, Redis, MemCached ...etc)

### ISSUE THREAD

**Issue by Korayem** [vanthoainguyen/Flatwhite#2]
Hey, I was wondering how do you control cache storage? I assume default storage is in-memory which won't work in cloud storage with horizontal scaling

**Comment by vantheshark** [comment]
Hey Korayem,

Just implement 
https://github.com/vanthoainguyen/Flatwhite/blob/master/Flatwhite/ICacheStore.cs
or 
https://github.com/vanthoainguyen/Flatwhite/blob/master/Flatwhite/IAsyncCacheStore.cs 

or both.

Then register it with 

https://github.com/vanthoainguyen/Flatwhite/blob/master/Flatwhite/Provider/ICacheStoreProvider.cs

A cacheStore should have a unique uint storeId which can be used with the cache attribute. 

``` csharp
Global.CacheStoreProvider.RegisterStore(new RedisCacheStore());
Global.CacheStoreProvider.RegisterAsyncStore(new SqlCacheStore());
```

You can implement ICacheStoreProvider and override it in Global.cs class
